language: generic
sudo: required
services:
    - docker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "clocks-mk2"
    env: "ClocksMk2-env"
    bucket_name: "elasticbeanstalk-us-east-2-107716788880"
    bucket_path: "clocks_curios"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

