language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nickwshaw/infinity-lists-app .

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Clocks and Curios"
    env: "ClocksAndCurios-env"
    bucket_name: "elasticbeanstalk-us-east-2-107716788880"
    bucket_path: "clocks_curios"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

