version: '3.4'

services:
  php:
    image: quay.io/sylius/php:latest
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - APP_SECRET=EDITME
      - DATABASE_URL=mysql://root@127.0.0.1/sylius_%kernel.environment%
      - MAILER_URL=smtp://localhost
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      # use a bind-mounted host directory, as we want to keep the sessions
      - ./var/sessions:/srv/sylius/var/sessions:rw
      # use a bind-mounted host directory, as we want to keep the media
      - ./public/media:/srv/sylius/public/media:rw

  nginx:
    # in production, we may want to use a static website hosting service
    image: quay.io/sylius/nginx:latest
    depends_on:
      - php
    volumes:
      # use a bind-mounted host directory, as we want to keep the media
      - ./public/media:/srv/sylius/public/media:ro
    ports:
      - "80:80"
